Add support for booting on T8012 (T2) SoC
AsahiLinux/m1n1 pull request #425
Opened 2024-12-01 16:27 UTC by asdfugil

This PR contains the changes required to boot the kernel on T2 per this LKML submission:

https://lore.kernel.org/asahi/20241201161942.36027-1-towinchenmi@gmail.com/T/#t

Overall T2 is similar to A10, and this takes care of the remaining:

- The ultra-narrow touch bar screen
- Some memory channels being unused on some devices
- Some ADT oddities
- Takes the memory intended for SSD cache and allow the kernel to use it

2025-02-03 11:52 UTC, marcan requested changes

2025-02-03 11:52 UTC, marcan commented on src/kboot.c
> +        /* Set x86 SSD Cache as OS memory, any potential driver would need the memory described
This won't work with an actual driver, it just abuses this region as main memory. If a driver were to use this, it would have to be described as reserved-memory (which automatically adds it to the list if mapped).

If you intend to ever actually support ANS here, then this probably needs to be kept reserved.

2025-02-03 11:52 UTC, marcan commented on src/kboot.c
> +        memreg[num_regions].start = cpu_to_fdt64(cache_min);
Missing bounds check.

2025-02-03 13:45 UTC, asdfugil commented on src/kboot.c
> +        /* Set x86 SSD Cache as OS memory, any potential driver would need the memory described
I think I will not describe this memory region for now, given that it might need new compatibles and stuff and that that part of the hardware is not well understood. In this case, this memory region only needs to be concerned while correcting `mem_size_actual`.

2025-02-08 16:29 UTC, asdfugil commented
Changes:

- Drop description of the SSD cache memory region in FDT setup.

2025-02-23 11:04 UTC, svenpeter42 requested changes

2025-02-23 11:04 UTC, svenpeter42 commented on src/kboot.c
> +    fdt_delprop(dt, dcs2_node, "apple,always-on");
Any reason this isn't just done in the devicetree?

2025-02-23 11:04 UTC, svenpeter42 commented on src/startup.c
> +             * Lower 512 MB intented for OS use, upper 512 or 1536 MB is some sort
Aren't we the OS? Or is there something else running there? And I'm not sure how this comments related to the code below which just computes the memory size.

The SSD cache is also present on >M1 fwiw, it's transparently handled by ANS firmware there and we can't even access it from the AP.

2025-02-23 11:06 UTC, svenpeter42 commented on src/kboot.c
> +        (adt_path_offset(adt, "/arm-io/disp0") > 0 || (chip_id != T8012 && chip_id != T7000))) {
Could you also add a comment about this condition? Looks somewhat confusing to me

2025-02-23 11:08 UTC, asdfugil commented on src/kboot.c
> +    fdt_delprop(dt, dcs2_node, "apple,always-on");
It can't be done in the device tree because the amount of memory and the amount of used memory channels depends on the storage configuration of the host Mac.

2025-02-23 11:10 UTC, asdfugil commented on src/startup.c
> +             * Lower 512 MB intented for OS use, upper 512 or 1536 MB is some sort
The comment help explain why the amount of reserved memory is so big. The upper memory region has something to do with exporting the ANS2 storage to the x86 CPU (which, on a T2 machine, is more like a big fat coprocessor of the T2).

2025-02-23 11:10 UTC, svenpeter42 commented on src/kboot.c
> +    fdt_delprop(dt, dcs2_node, "apple,always-on");
Oh, I totally missed the mem_size_actual check. I'd add a comment to this function then to explain what's going on here.

2025-02-23 11:18 UTC, svenpeter42 commented on src/startup.c
> +             * Lower 512 MB intented for OS use, upper 512 or 1536 MB is some sort
I think that upper memory is probably just Apple's variant of host memory buffers, i.e. using the main RAM as cache for the nvme drive. I don't even think that will need any driver support as long as you make sure not to clobber that memory region. When I briefly looked at how NVMe worked on T2 macs it seemed like it's just exporting the same MMIO interface we directly use on >M1 to the x86 CPU.

What I'm confused about here is that this comment talks about two reserved memory regions at different locations (lower and upper) but then the code just computes mem_size_actual.

2025-02-23 12:00 UTC, asdfugil commented on src/kboot.c
> +        (adt_path_offset(adt, "/arm-io/disp0") > 0 || (chip_id != T8012 && chip_id != T7000))) {
Sure, this condition is that there exist T8012 and T7000 devices with no display at all.

2025-02-23 12:02 UTC, svenpeter42 commented on src/kboot.c
> +        (adt_path_offset(adt, "/arm-io/disp0") > 0 || (chip_id != T8012 && chip_id != T7000))) {
Okay, but do they still have a /arm-io/disp0 node then?

2025-02-23 12:06 UTC, asdfugil commented on src/kboot.c
> +        (adt_path_offset(adt, "/arm-io/disp0") > 0 || (chip_id != T8012 && chip_id != T7000))) {
That node doesn't exist in their ADT.

2025-02-23 12:08 UTC, svenpeter42 commented on src/kboot.c
> +        (adt_path_offset(adt, "/arm-io/disp0") > 0 || (chip_id != T8012 && chip_id != T7000))) {
okay, so please take a step back and explain what you are trying to do here because this condition doesn't make much sense to me.

Right now we will init the framebuffer if
cur_boot_args.video.base is not null and either
    /arm-io/disp0 exists
        OR
    the chip is not T8012 and also not T7000

2025-02-23 12:23 UTC, asdfugil commented on src/kboot.c
> +        (adt_path_offset(adt, "/arm-io/disp0") > 0 || (chip_id != T8012 && chip_id != T7000))) {
This condition is to ensure on chips that definitely have a display attached, the framebuffer will be initialized if passed by iBoot, but now I am aware that some devices uses `/arm-io/dispext4` and this would actually break that, so how about:

Init framebuffer if base exists and (either chip is S5L8960X or the dimensions are not 640x1136)
(Would miss 640x1136 external display (?) does those exist (?))

2025-02-23 12:29 UTC, svenpeter42 commented on src/kboot.c
> +        (adt_path_offset(adt, "/arm-io/disp0") > 0 || (chip_id != T8012 && chip_id != T7000))) {
Does it even hurt to initialize the framebuffer when no display is connected?

2025-02-23 12:34 UTC, svenpeter42 commented on src/kboot.c
> +        (adt_path_offset(adt, "/arm-io/disp0") > 0 || (chip_id != T8012 && chip_id != T7000))) {
So why not just check if cur_boot_args.video.base is set and /chosen/framebuffer exists then?

2025-02-23 13:06 UTC, asdfugil commented
Changes: 
- Do not require `/chosen/framebuffer` to exist when booting Linux. Instead, use its existence to determine whether the device have a display or is capable to have a display connected. Skip framebuffer initialization if it does not exist
- Add comment about computing mem_size_actual for T2
- Add comment about disabling apple,always-on for unused memory channels in T2 pmgr.

2025-02-23 13:10 UTC, merged