Contain all display init logic within display.c
AsahiLinux/m1n1 pull request #429
Opened 2024-12-21 02:00 UTC by chadmed

Supersedes #428. Not sure if the changes to `display_get_config()` are the right thing to do here.

2024-12-21 02:02 UTC, chadmed commented
@asdfugil could you please test this on an iDevice to make sure it didn't break anything?

2024-12-21 05:27 UTC, asdfugil requested changes

2024-12-21 05:27 UTC, asdfugil commented on src/display.c
> +    has_dcp = !!adt_path_offset(adt, conf->dcp);
`adt_path_offset()` returns -1 on failure, so this breaks the has_dcp check.
```suggestion
    has_dcp = adt_path_offset(adt, conf->dcp) > 0;
```

2024-12-22 15:03 UTC, asdfugil approved these changes
Reviewed-by: Nick Chan <towinchenmi@gmail.com>

2025-01-20 22:26 UTC, merged