proxyclient: removed unused code
AsahiLinux/m1n1 pull request #96
Opened 2021-08-14 18:01 UTC by TophEvich

Little clean-up of unused proxyclient code.
Code used/referenced by commented out sections were taken into account and left behind to be used by it at a later point.

Signed-off-by: TophEvich <84676511+TophEvich@users.noreply.github.com>

2021-08-15 05:44 UTC, cristim commented
How did you detect this code? Did you use any linter for it? 

If so we should probably introduce a lint check in the PR workflow

2021-08-15 10:48 UTC, TophEvich commented
Sorry I have almost no python experience and am a python ecosystem novice. I just wanted to have a look at the code and used PyCharm for easy browsing. So I didn't set out to lint and I wouldn't know the pros and cons of each of the python linters that are out there.
So it was PyCharms internal "linter" which you can't use in CI. Also I don't know how much it would help, I think the nature of the project has quite a lot of code that might be hard for linters and as a result you'd have a lot of false positives (bad signal-to-noise ratio).
I only committed the parts where I was quite confident that the PyCharm was correct and also looked for commented out sections as they might be used in debugging sessions and so on.

Many of the errors/warnings/notices I ignored because it looked to me that it was meta programming/project layout related false positives.

2021-08-24 12:16 UTC, marcan requested changes

2021-08-24 12:16 UTC, marcan commented on proxyclient/m1n1/trace/__init__.py
> -    def read_cached(self, addr, width):
Let's keep this one orthogonal with read().

2021-08-24 12:16 UTC, marcan commented on proxyclient/m1n1/hv.py
> -            return self.handle_step(ctx)
Let's keep these orthogonal since ctx might be useful in the future.

2021-08-24 12:16 UTC, marcan commented on proxyclient/m1n1/hv.py
> +            self.del_tracer(zone, "AIC_IRQ")
Ah, this one's an actual bug :)

2021-08-24 12:16 UTC, marcan commented on proxyclient/m1n1/adt.py
> +def build_prop(name, v, t=None):
This is here because we might have path-dependent build rules in the future.

2021-08-24 12:16 UTC, marcan commented
The cleanup of unused variables looks good, but for the function args, a lot of the unused ones are there because they make sense and might become used in the future. I'd rather keep those.

2021-08-25 09:48 UTC, TophEvich commented
Rebased on latest main branch and put back in the sections you wanted because they are placeholder or too keep method signature symmetry in their respective "family".

2021-09-22 10:00 UTC, marcan approved these changes

2021-09-22 10:00 UTC, merged